### ISSUE TITLE
No space left on device on bm17

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#220]
This occurred while zipping the model state.   The server agent tries to create the zip file in the parent folder of the model state, to avoid copying data to a different device.  From the container's view the model state is written in /modelState which means that the zip file is created in "/" (the root dir).  The root dir may be within the container which may not have enough space to hold the zip file.

java.lang.Exception: Submission ID: 7531855
No space left on device
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:210)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:165)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:243)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:238)
	at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:343)
	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
	at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:360)
	at org.fuin.utils4j.Utils4J.zipDir(Utils4J.java:1547)
	at org.fuin.utils4j.Utils4J.zipDir(Utils4J.java:1571)
	at org.sagebionetworks.Archiver.archiveToSynapse(Archiver.java:100)
	at org.sagebionetworks.Training.uploadModelStateFolder(Training.java:725)
	at org.sagebionetworks.Training.updateTraining(Training.java:667)
	at org.sagebionetworks.Training.checkRunningTrainingSubmission(Training.java:587)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
	... 9 more
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Submission ID: 7531855
No space left on device
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:210)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:165)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:243)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:98)
	... 6 more
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:238)
	at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:343)
	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
	at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:360)
	at org.fuin.utils4j.Utils4J.zipDir(Utils4J.java:1547)
	at org.fuin.utils4j.Utils4J.zipDir(Utils4J.java:1571)
	at org.sagebionetworks.Archiver.archiveToSynapse(Archiver.java:100)
	at org.sagebionetworks.Training.uploadModelStateFolder(Training.java:725)
	at org.sagebionetworks.Training.updateTraining(Training.java:667)
	at org.sagebionetworks.Training.checkRunningTrainingSubmission(Training.java:587)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)

**Comment by tschaffter** [comment]
This error occurred on an Open Phase machine. bm17 has since been reinstalled. Every machine has the a cleanup script `/etc/cron.hourly/cleanup_docker_data.sh` that cleanup all the images (but the ones used by running containers) when 80% of the size of the docker data thinpool is reached.
