### ISSUE TITLE
Failure creating failure message

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#248]
This happened for submission 7769532 (Express Lane SC1 inference queue)

```
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Scoring - Submission failed
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
	at java.util.regex.Matcher.replaceAll(Matcher.java:906)
	at java.lang.String.replaceAll(String.java:2162)
	at org.sagebionetworks.MessageUtils.createScoringFailedMessage(MessageUtils.java:208)
	at org.sagebionetworks.Scoring$3.execute(Scoring.java:352)
	at org.sagebionetworks.Scoring$3.execute(Scoring.java:339)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.Scoring.checkRunningScoringSubmission(Scoring.java:339)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:129)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:220)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by brucehoff** [comment]
I fixed the bug in our challenge-agent code, updated bm04 and bm03, and reran the two submissions that were affected by this error (7772495 and 7769532).
