### ISSUE TITLE
No space left on device on bm04

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#256]
In addition to fixing the error need to restart submission 7773988.

The error occurred while reconstituting the model state (downloading and unzipping).  This is done in the folder, /data/model0 or /data/model1.

```
java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:936)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:228)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:120)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:936)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:228)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:120)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
```

```
DM Challenge Administrator:

Submission 7773988 to SCORE_SC_1 failed. Agent: bm04-1 

 The message is:

	No space left on device




Sincerely,

Challenge Administration
```

**Comment by tschaffter** [comment]
The root filesystem of bm04 uses only 31% of its space.

```
[root@bm04 ~]# df -h
Filesystem                   Size  Used Avail Use% Mounted on
/dev/sda3                     99G   30G   69G  31% /
devtmpfs                     252G     0  252G   0% /dev
tmpfs                        252G     0  252G   0% /dev/shm
tmpfs                        252G   33M  252G   1% /run
tmpfs                        252G     0  252G   0% /sys/fs/cgroup
/dev/mapper/data-dataset50    99G   61M   94G   1% /data/dataset50
/dev/mapper/data-dataset49    99G   61M   94G   1% /data/dataset49
/dev/mapper/data-dataset48    99G   61M   94G   1% /data/dataset48
/dev/mapper/data-dataset51    99G   61M   94G   1% /data/dataset51
/dev/sda1                    248M  159M   90M  64% /boot
```

Is there error reported when a container reaches its maximum size (10 GB)?

**Comment by brucehoff** [comment]
> Is there error reported when a container reaches its maximum size (10 GB)?
Not to my knowledge.  Also there is no check that the provided model state is within any limit.  I will check the size of the file that the participant chose for the model state.

**Comment by tschaffter** [comment]
From Bruce:

> Would you please have a look at this issue?  The agent encountered an 'out of space' error while reconstituting the model state, downloading and unzipping into the folder /data/model0 or /data/model1 on bm04.

@brucehoff Do you place the archive in /data/model0 and extract its content at the same location?

**Comment by tschaffter** [comment]
Could it be that the model state archive is downloaded to /data/model0 and extracted there? /data/model0 should not be expected to be larger than the uncompressed model state.

**Comment by brucehoff** [comment]
> @brucehoff Do you place the archive in /data/model0 and extract its content at the same location?

> @brucehoff Do you place the archive in /data/model0 and extract its content at the same location?

Yes, the code is lines 227-230 here:
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/blob/master/src/main/java/org/sagebionetworks/Scoring.java
It downloads to /data/model0/<uuid>.zip and unzips into /data/model0

**Comment by brucehoff** [comment]
The model state in this submission is
https://www.synapse.org/#!Synapse:syn7773969
7773947_mik2015-simple-cnn-vgg16_model_state.zip
which is 473 MB, zipped.

**Comment by brucehoff** [comment]
> Could it be that the model state archive is downloaded to /data/model0 and extracted there? 
Yes, exactly.  Where should the model state be downloaded to prior to extraction?

**Comment by tschaffter** [comment]
That's the problem. /data/model0 is not large enough to contain the uncompressed model state in addition to the compressed model state. Download archive instead to scratch and uncompress from there to /data/model0.

**Comment by brucehoff** [comment]
> download it somewhere on the root filesystem

Can I use a folder like `/data/unzip`, i.e. inside `/data` and 'next to' model0?

**Comment by tschaffter** [comment]
I don't think there is a need for me to create a dedicated partition for that. If you create the folder `/data/unzip` it's going to use the root filesystem, which is totally fine if you systematically remove the compressed archive once extracted.

**Comment by tschaffter** [comment]
You can download the archive an

**Comment by brucehoff** [comment]
I changed the agent to download into /root/tempDir and then unzip into /data/modelStateN.  
I updated the scoring agent on bm03 and bm04.
I restarted 7773988, 7774856 and verified they got past this error.
