### ISSUE TITLE
concurrency error when updating uploaded data table

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#283]
Archiver.updateUploadedData() should handle the case in which the etag is out of date when it tries to update the table.

```
Row id: 199 has been changed since last read.  Please get the latest value for this row and then attempt to update it again.
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:156)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:216)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.sagebionetworks.client.exceptions.SynapseConflictingUpdateException: Row id: 199 has been changed since last read.  Please get the latest value for this row and then attempt to update it again.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:342)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:733)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:559)
	at org.sagebionetworks.client.SynapseClientImpl.getAsynchJobResponse(SynapseClientImpl.java:3832)
	at org.sagebionetworks.client.SynapseClientImpl.getAsyncResult(SynapseClientImpl.java:3821)
	at org.sagebionetworks.client.SynapseClientImpl.appendRowSetToTableGet(SynapseClientImpl.java:5811)
	at org.sagebionetworks.client.SynapseClientImpl.appendRowsToTable(SynapseClientImpl.java:5842)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.appendRowsToTable(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:53)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:50)
	at com.sun.proxy.$Proxy24.appendRowsToTable(Unknown Source)
	at org.sagebionetworks.Archiver.updateUploadedData(Archiver.java:253)
	at org.sagebionetworks.Archiver.archiveToSynapse(Archiver.java:176)
	at org.sagebionetworks.Archiver.uploadLogs(Archiver.java:323)
	at org.sagebionetworks.Training.updateJob(Training.java:745)
	at org.sagebionetworks.Training.updateTraining(Training.java:582)
	at org.sagebionetworks.Training.checkRunningTrainingSubmission(Training.java:502)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:197)
	... 9 more
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Submission ID: 7801177
Row id: 199 has been changed since last read.  Please get the latest value for this row and then attempt to update it again.
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:156)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:216)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:83)
	... 6 more
Caused by: org.sagebionetworks.client.exceptions.SynapseConflictingUpdateException: Row id: 199 has been changed since last read.  Please get the latest value for this row and then attempt to update it again.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:342)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:733)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:559)
	at org.sagebionetworks.client.SynapseClientImpl.getAsynchJobResponse(SynapseClientImpl.java:3832)
	at org.sagebionetworks.client.SynapseClientImpl.getAsyncResult(SynapseClientImpl.java:3821)
	at org.sagebionetworks.client.SynapseClientImpl.appendRowSetToTableGet(SynapseClientImpl.java:5811)
	at org.sagebionetworks.client.SynapseClientImpl.appendRowsToTable(SynapseClientImpl.java:5842)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.appendRowsToTable(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:53)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:50)
	at com.sun.proxy.$Proxy24.appendRowsToTable(Unknown Source)
	at org.sagebionetworks.Archiver.updateUploadedData(Archiver.java:253)
	at org.sagebionetworks.Archiver.archiveToSynapse(Archiver.java:176)
	at org.sagebionetworks.Archiver.uploadLogs(Archiver.java:323)
	at org.sagebionetworks.Training.updateJob(Training.java:745)
	at org.sagebionetworks.Training.updateTraining(Training.java:582)
	at org.sagebionetworks.Training.checkRunningTrainingSubmission(Training.java:502)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:197)
	... 9 more


```

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/ba5e17bb6c24e3b3a0b5de0e01a0368c10d39b18
