### ISSUE TITLE
Permissions error when running an inference submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#286]
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Scoring - Selected and locked 7804625 for SCORE_SC_1
18:46:20.306 [org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Nov 30, 2016 6:46:20 PM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Will not retry: 403 You do not have READ permission for the requested entity.
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Scoring - Submission failed
org.sagebionetworks.client.exceptions.SynapseForbiddenException: You do not have READ permission for the requested entity.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:334)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:733)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:559)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:541)
	at org.sagebionetworks.client.SynapseClientImpl.getEntity(SynapseClientImpl.java:1912)
	at org.sagebionetworks.client.SynapseClientImpl.getEntityBenefactor(SynapseClientImpl.java:1391)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.getEntityBenefactor(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:53)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:50)
	at com.sun.proxy.$Proxy24.getEntityBenefactor(Unknown Source)
	at org.sagebionetworks.SubmissionUtils.validateEntityAccess(SubmissionUtils.java:165)
	at org.sagebionetworks.validation.ScoringValidator.validateAccess(ScoringValidator.java:117)
	at org.sagebionetworks.validation.ScoringValidator.retrieveAndValidateSubmissionParameters(ScoringValidator.java:93)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:207)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:123)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.sagebionetworks.client.exceptions.SynapseForbiddenException: You do not have READ permission for the requested entity.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:334)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:733)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:559)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:541)
	at org.sagebionetworks.client.SynapseClientImpl.getEntity(SynapseClientImpl.java:1912)
	at org.sagebionetworks.client.SynapseClientImpl.getEntityBenefactor(SynapseClientImpl.java:1391)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.getEntityBenefactor(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:53)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:50)
	at com.sun.proxy.$Proxy24.getEntityBenefactor(Unknown Source)
	at org.sagebionetworks.SubmissionUtils.validateEntityAccess(SubmissionUtils.java:165)
	at org.sagebionetworks.validation.ScoringValidator.validateAccess(ScoringValidator.java:117)
	at org.sagebionetworks.validation.ScoringValidator.retrieveAndValidateSubmissionParameters(ScoringValidator.java:93)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:207)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:123)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	... 6 more

**Comment by brucehoff** [comment]
The submission is:
```
model_state=syn7347524
inference=docker.synapse.org/syn7347524/tmii_2016_10_28as_format_fix@sha256:9729471b01f126c0457b281e4271c793ae8ca4e5bb0b9df2fd078f6aa16e4bee
```

**Comment by brucehoff** [comment]
The problem here is that the user has not shared the two entities in the submitted file with the challenge infrastructure.  This change creates an informative error message:

https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/fda8fcc34d5e8e33375ccc93734f54d410578b49

**Comment by brucehoff** [comment]
The participant says:
```
When I used *file* (syn7486777), then submission was failed with an error message “syn7486777 is not accessible by the submission creators.” I requested the access but didn’t get any answer.
```
