### ISSUE TITLE
bm04 : No space left on device

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#288]
In this case the user is trying to use a 'model state' from the open access phase in the express lane.  The file in question is syn7486777.  The compressed archive is 950.768 MB.  The model state was created on bm23 (see submission 7482793) and ran into problems unzipping on bm04.  The bm04 share is 970MB.  `df -m` returns
```
/dev/mapper/data-model187         976      3       907   1% /data/model187
/dev/mapper/data-model186         976      3       907   1% /data/model186
/dev/mapper/data-model183         976      3       907   1% /data/model183
```
The shares are the same size on bm23:
```
/dev/mapper/data-model2         976       3       907   1% /data/model2
/dev/mapper/data-model1         976       3       907   1% /data/model1
```
I guess the problem is that there's some overhead when unzipping.

```
java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:936)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:232)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:123)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:936)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:232)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:123)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	... 6 more
```

**Comment by tschaffter** [comment]
> Do you think we might make the model-state volumes larger to avoid this problem?

The same error may occur with a larger model-state volume. The way to go is to uncompress the model state somewhere else before move it to `/modelState`.

**Comment by brucehoff** [comment]
I reproduced the problem from the unix command line on bm04:
```
unzip 7482793_tmii_2016_10_28a_model_state.zip -d /data/model3
Archive:  7482793_tmii_2016_10_28a_model_state.zip
  inflating: /data/model3/model.ckpt.meta  
  inflating: /data/model3/checkpoint  
  inflating: /data/model3/model.ckpt  
/data/model3/model.ckpt:  write error (disk full?).  Continue? (y/n/^C) n
```

**Comment by tschaffter** [comment]
@brucehoff Have you seen my last comment? Do you agree with the suggested solution?

**Comment by brucehoff** [comment]
@tschaffter yes, I read your comment.  The suggested solution involves unzipping in two steps (first unzip, then move the content) versus the current approach of unzipping directly into the target location, but that doesn't seem unreasonable.

It looks like the target location is big enough for the content:
```
[root@bm04 tempDir]# ls -al 7482793_tmii_2016_10_28a_model_state.zip
-rw-rw-r--. 1 dreamuser dreamuser 996952197 Dec  1 08:59 7482793_tmii_2016_10_28a_model_state.zip
[root@bm04 tempDir]# df -k | grep model3
/dev/mapper/data-model30       999320      2564    927944   1% /data/model30
/dev/mapper/data-model3        999320    982936         0 100% /data/model3
```
i.e. 999320>996952, but only by 0.2%.  I'm guessing that there's some overhead when unzipping into a target location.  The next step is to try unzipping into /root/tempDir and moving the content into /data/modelX.

**Comment by brucehoff** [comment]
Update:  I unzipped and looked at the content.  It seems the unzipped content is BIGGER than 1GB:
```
[root@bm04 tempDir]# unzip 7482793_tmii_2016_10_28a_model_state.zip -d temp
Archive:  7482793_tmii_2016_10_28a_model_state.zip
  inflating: temp/model.ckpt.meta    
  inflating: temp/checkpoint         
  inflating: temp/model.ckpt         
  inflating: temp/out_train.txt      
[root@bm04 tempDir]# cd temp/
[root@bm04 temp]# ls -al
total 1049568
drwxr-xr-x.  2 root root         82 Dec  1 09:18 .
drwxr-xr-x. 15 root root       4096 Dec  1 09:18 ..
-rw-r--r--.  1 root root        101 Oct 31 20:05 checkpoint
-rw-r--r--.  1 root root 1074255520 Oct 31 20:05 model.ckpt
-rw-r--r--.  1 root root     483829 Oct 31 20:05 model.ckpt.meta
-rw-r--r--.  1 root root        898 Oct 31 20:06 out_train.txt
```

**Comment by brucehoff** [comment]
Here's what the file system looks like on bm23, where the model-state was created.  The volume sizes look exactly the same as on bm04.
```
[dreamuser@bm23 model0]$ df
Filesystem                  1K-blocks       Used   Available Use% Mounted on
/dev/sda3                   935388932   52663920   882725012   6% /
devtmpfs                    264028344          0   264028344   0% /dev
tmpfs                       264041584          0   264041584   0% /dev/shm
tmpfs                       264041584     387060   263654524   1% /run
tmpfs                       264041584          0   264041584   0% /sys/fs/cgroup
/dev/sda1                      253676     163964       89712  65% /boot
/dev/mapper/data-model4        999320       2564      927944   1% /data/model4
/dev/mapper/data-model0        999320       2564      927944   1% /data/model0
/dev/mapper/data-model3        999320       2564      927944   1% /data/model3
/dev/mapper/data-dataset3 10652622752    2541204 10113194252   1% /data/dataset3
/dev/mapper/data-dataset0 10652622752   58394040 10057341416   1% /data/dataset0
/dev/mapper/data-dataset4 10652622752      73752 10115661704   1% /data/dataset4
/dev/mapper/data-dataset1 10652622752   36155712 10079579744   1% /data/dataset1
/dev/mapper/data-dataset2 10652622752      73736 10115661720   1% /data/dataset2
/dev/mapper/data-scratch1   206292968      61464   195729360   1% /data/scratch1
/dev/mapper/data-model2        999320       2548      927960   1% /data/model2
/dev/mapper/data-model1        999320       2576      927932   1% /data/model1
/dev/mapper/data-scratch0   206292968      61464   195729360   1% /data/scratch0
/dev/mapper/data-data      8522076068 7003307152  1089255804  87% /data/data
tmpfs                        52808320          0    52808320   0% /run/user/0
tmpfs                        52808320          0    52808320   0% /run/user/1000
```

**Comment by brucehoff** [comment]
@tschaffter : It seems like a simple work-around is to make the model-state volumes on the scoring machines slightly larger.  What do you think?

**Comment by tschaffter** [comment]
Yes, I can add 1 GB of extra space to the `/data/modelX` partitions on the scoring machines. Let me know when I can do the update safely and on which machines.

**Comment by brucehoff** [comment]
@tschaffter:
> Yes, I can add 1 GB of extra space to the /data/modelX partitions on the scoring machines
Thanks.  Please note, we only use /data/model0 and /data/model1.  We don't need any other /data/modelX volumes.

> Let me know when I can do the update safely and on which machines.
You can do it now.   The immediate need is on bm03 and bm04.  I just stopped the agents, ensuring that the volumes are not used, but please also modify the other machines slated for scoring.  According to your DREAM 11 Cloud status document that includes bm06 .

Thank you.

**Comment by tschaffter** [comment]
Done:

```
[root@bm03 ~]# df -h | grep 2.0G
/dev/mapper/data-model0    2.0G  3.0M  1.9G   1% /data/model0
/dev/mapper/data-model1    2.0G  3.0M  1.9G   1% /data/model1
[root@bm04 ~]# df -h | grep 2.0G
/dev/mapper/data-model0      2.0G  3.0M  1.9G   1% /data/model0
/dev/mapper/data-model1      2.0G  961M  916M  52% /data/model1
[root@bm06 ~]# df -h | grep 2.0G
/dev/mapper/data-model1    2.0G  3.0M  1.9G   1% /data/model1
/dev/mapper/data-model0    2.0G  3.0M  1.9G   1% /data/model0
```

Before closing this ticket I need to modify the provisioning script, which will take some time do it cleanly because I don't have a different configuration for training and scoring machines.

**Comment by brucehoff** [comment]
I restarted inference submission 7804932 on bm04 and verified that it got past the volume overrun issue.

**Comment by tschaffter** [comment]
As mentioned above, I've already update the provisioning script.
