### ISSUE TITLE
Multiple challenge agents stopped

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#296]
SEVERE: Will not retry: 400 null is not a valid Synapse ID.
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Training - Submission failed
org.sagebionetworks.client.exceptions.SynapseBadRequestException: null is not a valid Synapse ID.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:340)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:745)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:568)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:550)
	at org.sagebionetworks.client.SynapseClientImpl.querySynapse(SynapseClientImpl.java:3952)
	at org.sagebionetworks.client.SynapseClientImpl.query(SynapseClientImpl.java:2208)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.query(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:53)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:50)
	at com.sun.proxy.$Proxy24.query(Unknown Source)
	at org.sagebionetworks.SubmissionUtils.getEntityIdForDockerImage(SubmissionUtils.java:146)
	at org.sagebionetworks.validation.TrainingValidator.validateAccess(TrainingValidator.java:158)
	at org.sagebionetworks.validation.TrainingValidator.retrieveAndValidateTrainingParams(TrainingValidator.java:125)
	at org.sagebionetworks.validation.TrainingValidator.validateAndInitSubmissionBundle(TrainingValidator.java:90)
	at org.sagebionetworks.Training.selectAndLockSubmissionForTraining(Training.java:241)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:184)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:157)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:219)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.sagebionetworks.client.exceptions.SynapseBadRequestException: null is not a valid Synapse ID.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:340)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:745)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:568)
	at org.sagebionetworks.client.SharedClientConnection.getJson(SharedClientConnection.java:550)
	at org.sagebionetworks.client.SynapseClientImpl.querySynapse(SynapseClientImpl.java:3952)
	at org.sagebionetworks.client.SynapseClientImpl.query(SynapseClientImpl.java:2208)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.query(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:53)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:58)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:50)
	at com.sun.proxy.$Proxy24.query(Unknown Source)
	at org.sagebionetworks.SubmissionUtils.getEntityIdForDockerImage(SubmissionUtils.java:146)
	at org.sagebionetworks.validation.TrainingValidator.validateAccess(TrainingValidator.java:158)
	at org.sagebionetworks.validation.TrainingValidator.retrieveAndValidateTrainingParams(TrainingValidator.java:125)
	at org.sagebionetworks.validation.TrainingValidator.validateAndInitSubmissionBundle(TrainingValidator.java:90)
	at org.sagebionetworks.Training.selectAndLockSubmissionForTraining(Training.java:241)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:184)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:157)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:219)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	... 6 more

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/296
