### ISSUE TITLE
bm17 has insufficient 'data blocks'

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#379]
The error when trying to create a container is
```
devmapper: Thin Pool has 148678 free data blocks which is less than minimum required 163840 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior
```
See the source (Java stack trace on agent bm17-train-1, below).  

@tschaffter Could you have a look?

 I will move teams off bm17 until resolved.

```
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"devmapper: Thin Pool has 148678 free data blocks which is less than minimum required 163840 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:34)
	at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:15)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:177)
```

**Comment by tschaffter** [comment]
Fixed.

Initially, the cleanup script used information from docker to know when to clean the unused images based on how much of the data thinpool is used. Because we had issue with docker sometimes not responding, I changed the script to look at the usage of the root filesystem to determine when to do the cleanup, which include more than cleaning docker since I recently figured out that crashes generate 4-5 GB files. The mistake that I did when referring to how much the root filesystem is was to forget that while the original ten machines have a root filesystem of 100 GB, the latest machines ordered have a root filesystem larger. On bm17, the cleanup threshold is then unadapted and the cleanup script never started. Until the end of this round, I've changed the cleanup threshold on the machines that have a root filesystem larger than the expected 100 GB (bm11 to bm23).

New cleanup script impreovement tracked here: #387 

@brucehoff Docker and nvml agents are running. Can you restart the Challenge agents and close this issue?

Thanks!

**Comment by brucehoff** [comment]
challenge agents are running again on bm17
