### ISSUE TITLE
bm09: /usr/local/lib/libopencv_cudafilters.so.3.2.0: no space left on device

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#405]
All processing on bm09 has stopped.  The root cause seems to be "/usr/local/lib/libopencv_cudafilters.so.3.2.0: no space left on device"

```
Failed to start preprocessing phase of 7892021.  Message is Unable to pull image docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce after 6 try(ies).
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:206)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:157)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:219)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	... 6 more
Caused by: java.lang.Exception: Failed to start preprocessing phase of 7892021.  Message is Unable to pull image docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce after 6 try(ies).
	at org.sagebionetworks.Training.startPreprocessing(Training.java:426)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:363)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:188)
	... 9 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Unable to pull image docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce after 6 try(ies).
	at org.sagebionetworks.DockerUtils.pullImageWithRetry(DockerUtils.java:236)
	at org.sagebionetworks.DockerUtils.createContainer(DockerUtils.java:251)
	at org.sagebionetworks.DockerUtils.createModelContainer(DockerUtils.java:199)
	at org.sagebionetworks.Training.startPreprocessing(Training.java:402)
	... 11 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/local/lib/libopencv_cudafilters.so.3.2.0: no space left on device
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at org.sagebionetworks.DockerUtils.pullImageWithRetry(DockerUtils.java:220)
	... 14 more
```

**Comment by tschaffter** [comment]
Today at 10:40 EST, the disk usage reached 88.7% according to Sysdig, followed by a cleanup. The disk usage and docker data thinpool usage is currently OK.

I tried to pull the image `docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce` but couldn't.

```
[root@vm ~]# docker login docker.synapse.org
Username (tschaffter): 
Password: 
Login Succeeded
[root@vm ~]# docker pull docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce

Please login prior to pull:
Username (tschaffter): 
Password: 
Error response from daemon: unauthorized: authentication required
[root@vm ~]#
```

Can you check what the size of this image is?

**Comment by brucehoff** [comment]
I tried the 'docker pull' on my laptop:
```
docker pull docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce

Please login prior to pull:
Username (brucehoff): dmchallengeit
Password: 
sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce: Pulling from syn7415408/cpi14
8d30e94188e7: Already exists 
42dc503c149f: Already exists 
703b89f2b631: Already exists 
6e90add89e05: Already exists 
d3f1d75635c9: Already exists 
360419337e2c: Already exists 
6534d6abffcf: Already exists 
9f89baa7ee1d: Already exists 
887d4d260c5f: Already exists 
3c39b2ebc485: Already exists 
97819e52d579: Already exists 
014191e01c27: Already exists 
7b9c92158f0d: Already exists 
28561eb9c751: Already exists 
02c241d982d9: Already exists 
88b8bd81cb4e: Pull complete 
0c538be2093b: Pull complete 
e7f6c4890889: Pull complete 
d63df333e1d7: Pull complete 
e71d87541f9c: Pull complete 
4d6b8d89a3af: Pull complete 
8bb65a94f58b: Pull complete 
ab626821e979: Pull complete 
712d9e062a96: Pull complete 
0a1383c5873e: Pull complete 
b9269ac38c99: Pull complete 
51a7d0b75e44: Pull complete 
54b772274f37: Extracting [=========>                                         ] 201.7 MB/1.009 GB
c710fcb653e8: Downloading [==================================================>] 994.5 MB/994.5 MB
43797bea416e: Download complete 
b4fce40d85ad: Download complete 
e36e69a568b4: Download complete 
4b614599d45c: Download complete 
ea41414f10e2: Download complete 
67cf991213da: Download complete 
01a6158eec69: Download complete 
write /mnt/sda1/var/lib/docker/tmp/GetImageBlob251065563: no space left on device
```

**Comment by brucehoff** [comment]
The 'docker pull' completed on another machine.  The image size is 17GB, see below.
```
sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce: Pulling from syn7415408/cpi14
8d30e94188e7: Pull complete 
42dc503c149f: Pull complete 
703b89f2b631: Pull complete 
6e90add89e05: Pull complete 
d3f1d75635c9: Pull complete 
360419337e2c: Pull complete 
6534d6abffcf: Pull complete 
9f89baa7ee1d: Pull complete 
887d4d260c5f: Pull complete 
3c39b2ebc485: Pull complete 
97819e52d579: Pull complete 
014191e01c27: Pull complete 
7b9c92158f0d: Pull complete 
28561eb9c751: Pull complete 
02c241d982d9: Pull complete 
88b8bd81cb4e: Pull complete 
0c538be2093b: Pull complete 
e7f6c4890889: Pull complete 
d63df333e1d7: Pull complete 
e71d87541f9c: Pull complete 
4d6b8d89a3af: Pull complete 
8bb65a94f58b: Pull complete 
ab626821e979: Pull complete 
712d9e062a96: Pull complete 
0a1383c5873e: Pull complete 
b9269ac38c99: Pull complete 
51a7d0b75e44: Pull complete 
54b772274f37: Pull complete 
c710fcb653e8: Pull complete 
43797bea416e: Pull complete 
b4fce40d85ad: Pull complete 
e36e69a568b4: Pull complete 
4b614599d45c: Pull complete 
ea41414f10e2: Pull complete 
67cf991213da: Pull complete 
01a6158eec69: Pull complete 
Digest: sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce
Status: Downloaded newer image for docker.synapse.org/syn7415408/cpi14@sha256:f706218b27ff769b8ae45142f7c55cf0c3201d675103ba3eca6bee9d2fdd55ce
[~/Documents]  docker images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
docker.synapse.org/syn7415408/cpi14         <none>              d225295a2a1c        42 hours ago        17.01 GB
brucehoff/importissues                      latest              f21da0c7182c        8 weeks ago         713.1 MB
<none>                                      <none>              bfcb81b7a929        8 weeks ago         713.1 MB
<none>                                      <none>              fbade039c798        8 weeks ago         713.1 MB
<none>                                      <none>              ba3af379cd38        8 weeks ago         713.1 MB
<none>                                      <none>              ed5d9859612b        8 weeks ago         713.1 MB
<none>                                      <none>              ef7fc40a7f54        8 weeks ago         713.1 MB
<none>                                      <none>              ee9a73929079        8 weeks ago         713.1 MB
<none>                                      <none>              5cced726dbad        8 weeks ago         713.1 MB
<none>                                      <none>              10fdef6bcdf0        8 weeks ago         713.1 MB
<none>                                      <none>              c665b9756b5d        8 weeks ago         713.1 MB
python                                      2.7                 77cf0ea98df6        8 weeks ago         673.2 MB
docker.synapse.org/syn3572263/hello-world   latest              c54a2cc56cbb        5 months ago        1.848 kB
ubuntu                                      latest              44776f55294a        8 months ago        120.1 MB
benhall/curl                                latest              97ae202f600e        14 months ago       8.748 MB
```

**Comment by tschaffter** [comment]
This is too large for the current setup. Currently, docker can store up to about 90 GB of containers on the machines. We have to set a limit to the size of the container that the participants can submit. If they submit a container of 100 GB, docker will crash systematically.

By default, container can grow up to a total container size of 10 GB (default docker settings). However, participants can build larger container. The question is what is the maximum size that we want to allow. Agent should check the size before downloading the image and return an appropriate error message if it doesn't satisfy the condition.

One of my task next week will be to see if we can increase the Docker pool size, however there are restrictions on the physical disk that I can use (regarding disk IO speed). To make a long story short, what about limiting the size of the container to 10 GB? This should be enough to allow a training or scoring container to include a trained model.

**Comment by brucehoff** [comment]
> Agent should check the size before downloading the image and return an appropriate error message if it doesn't satisfy the condition.

Yes, that makes sense.  At the moment I don't know how to do this, but I agree that we should.

**Comment by brucehoff** [comment]
The root cause is https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/416 and this issue can be tracked there.
