### ISSUE TITLE
bm08: stderr: write /usr/lib/nvidia-367/libnvidia-compiler.so.367.57: no space left on device

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#409]
The Express Lane is now completely down.

```
ERROR org.sagebionetworks.Training - Submission failed
java.lang.Exception: Submission ID: 7894062
Unable to pull image docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:35fff23a1bc1e2ad79cd7e21ebd8c643630cb4b24b47ad6dbca515cdd2be3b6b after 6 try(ies).
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:206)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:157)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:219)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Unable to pull image docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:35fff23a1bc1e2ad79cd7e21ebd8c643630cb4b24b47ad6dbca515cdd2be3b6b after 6 try(ies).
	at org.sagebionetworks.DockerUtils.pullImageWithRetry(DockerUtils.java:236)
	at org.sagebionetworks.DockerUtils.createContainer(DockerUtils.java:251)
	at org.sagebionetworks.DockerUtils.createModelContainer(DockerUtils.java:199)
	at org.sagebionetworks.Training.startTraining(Training.java:464)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:365)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:188)
	... 9 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/lib/nvidia-367/libnvidia-compiler.so.367.57: no space left on device
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at org.sagebionetworks.DockerUtils.pullImageWithRetry(DockerUtils.java:220)
	... 14 more
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Submission ID: 7894062
Unable to pull image docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:35fff23a1bc1e2ad79cd7e21ebd8c643630cb4b24b47ad6dbca515cdd2be3b6b after 6 try(ies).
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:206)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:157)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:219)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	... 6 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Unable to pull image docker.synapse.org/syn7890435/dm-ls-train-dl@sha256:35fff23a1bc1e2ad79cd7e21ebd8c643630cb4b24b47ad6dbca515cdd2be3b6b after 6 try(ies).
	at org.sagebionetworks.DockerUtils.pullImageWithRetry(DockerUtils.java:236)
	at org.sagebionetworks.DockerUtils.createContainer(DockerUtils.java:251)
	at org.sagebionetworks.DockerUtils.createModelContainer(DockerUtils.java:199)
	at org.sagebionetworks.Training.startTraining(Training.java:464)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:365)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:188)
	... 9 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/lib/nvidia-367/libnvidia-compiler.so.367.57: no space left on device
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at org.sagebionetworks.DockerUtils.pullImageWithRetry(DockerUtils.java:220)
	... 14 more
```

**Comment by tschaffter** [comment]
- Does that mean only the training machines (bm08, bm09) or also the scoring machine (bm04)
- Where does the error that you report come from (machine, log file)?

First thing is to check the disk usage and docker data thinpool usage.

```
[root@bm09 ~]# df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        99G   39G   61G  39% /
[root@bm09 ~]# docker info | grep "Data Space"
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Data Space Used: 4.257 GB
 Data Space Total: 107.4 GB
 Data Space Available: 65 GB
```

Then check if the machines have rebooted (it is the case for bm08 BUT NOT for bm09):
```
[root@bm08 ~]# last reboot
reboot   system boot  3.10.0-514.2.2.e Wed Dec 21 10:02 - 09:01  (22:59)    
reboot   system boot  3.10.0-514.el7.x Tue Dec 13 13:25 - 09:01 (8+19:36)
[root@bm09 ~]# last reboot
reboot   system boot  3.10.0-327.36.3. Fri Nov  4 09:42 - 09:02 (48+00:19)
```

In the case of bm09, can you know why the two agents stopped running (e.g. from their log file)?

Can we generate a table with the following columns for the docker containers that are running when a Challenge agent stop running?
- docker image with digest
- name of the team
- hostname of the machine
- index of the agent that stopped

From Sysdig panel that report the usage of the root filesystem, it doesn't appear as bm08 or bm09 saturated it over the course of the past two days.

- Question: Do the Challenge agent containers store data inside them? Is it possible that they become larger than the 10 GB limit per container and stop running?

For me, the training express lane can be restarted on bm08 and bm09.

**Comment by brucehoff** [comment]
The root cause is https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/416 and this issue can be tracked there.
