### ISSUE TITLE
Add retry for file upload

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#415]
Need some automated retry logic here:
```
Missing 1 part(s).  All parts must be successfully added before a file upload can be completed.
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:206)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:157)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:219)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.sagebionetworks.client.exceptions.SynapseBadRequestException: Missing 1 part(s).  All parts must be successfully added before a file upload can be completed.
	at org.sagebionetworks.client.SharedClientConnection.convertHttpResponseToException(SharedClientConnection.java:340)
	at org.sagebionetworks.client.SharedClientConnection.convertResponseBodyToJSON(SharedClientConnection.java:745)
	at org.sagebionetworks.client.SharedClientConnection.putJson(SharedClientConnection.java:541)
	at org.sagebionetworks.client.SynapseClientImpl.asymmetricalPut(SynapseClientImpl.java:2660)
	at org.sagebionetworks.client.SynapseClientImpl.completeMultipartUpload(SynapseClientImpl.java:7571)
	at org.sagebionetworks.client.MultipartUpload.uploadFile(MultipartUpload.java:96)
	at org.sagebionetworks.client.SynapseClientImpl.multipartUpload(SynapseClientImpl.java:7577)
	at org.sagebionetworks.client.SynapseClientImpl.multipartUpload(SynapseClientImpl.java:7591)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy24.multipartUpload(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:54)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:55)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:51)
	at com.sun.proxy.$Proxy24.multipartUpload(Unknown Source)
	at org.sagebionetworks.Archiver.archiveToSynapse(Archiver.java:110)
	at org.sagebionetworks.Archiver.archiveToSynapseWithSizeLimit(Archiver.java:227)
	at org.sagebionetworks.Archiver.uploadLogs(Archiver.java:441)
	at org.sagebionetworks.Training.updateJob(Training.java:757)
	at org.sagebionetworks.Training.updateTraining(Training.java:591)
	at org.sagebionetworks.Training.checkRunningTrainingSubmission(Training.java:511)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:198)
```

**Comment by brucehoff** [comment]
This issue hasn't recurred in 27 days so it's probably not worth doing.
