### ISSUE TITLE
inference submission can't write to /output

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#440]
A long running inference submission, 7898165, just terminated.   I looked at the logs and found:
```
Traceback (most recent call last):
  File "dm-preprocess-scoring.py", line 170, in <module>
    nulis(dicConfidence,predPath)
  File "dm-preprocess-scoring.py", line 60, in nulis
    with open(predPath,'wb') as csvfile: #Direktori untuk output predictions.tsv
IOError: [Errno 2] No such file or directory: '/output/predictions.tsv'
```
It appears that the model tried to write to /output but was unable to do so.  I recall a comment on the forum complaining about a similar problem, so there may actually be a problem we have to investigate in our infrastructure.

The design is as follows:
Agent X (X=1,2) on the server has directory `/root/tempDir<X-1>` mounted as `/tempDir`.  It creates a subfolder <UUID> and checks that `/tempDir/<UUID>` exists.  It then creates a container for the inference submission, mounting `/root/tempDir<X-1>/UUID` as `/output`.  

Update:  I believe I know where the error lies:
When the agent creates `/root/tempDir<X-1>` it adds `deleteOnExit()`.  This may mean that if the agent is stopped and restarted that it deletes `/root/tempDir<X-1>/UUID` on the host.

**Comment by brucehoff** [comment]
I think this issue shares a common root cause: https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/435

I responded on the forum: https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1439

We need to rerun 7898165 and 7892426, as well as search for other affected submissions.   Two ways to do this:  (1) Broadcast a request to all participants, asking what error they encountered, (2) review outgoing email messages to find ones containing an error message that `/output` was not available.

**Comment by brucehoff** [comment]
I restarted the agents on bm16 (which would otherwise have been kept off-line for Thomas S. to do maintenance) and restarted 7898165 and 7892426.  bm16 picked up those two submissions and it rerunning them.
