### ISSUE TITLE
Missing agents on bm16

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#450]
There is only one agent running on bm16. Is that normal?

```
[root@bm16 ~]# docker ps
CONTAINER ID        IMAGE                                                                                                              COMMAND                  CREATED             STATUS              PORTS               NAMES
d867ef45a75b        docker.synapse.org/syn7500070/dm-scoring@sha256:ac955e4a989d27308f9f9e719ee7525bfe05e5a523aa2901901e7177b919bec3   "/sc1_infer.sh"          4 days ago          Up 4 days                               7892426.bm16-2.SCORE_SC_1.SCORING
c4feb9c30d26        docker.synapse.org/syn7500070/dm-scoring@sha256:f6faa4dc26011060436c73bb16e4e8aa058711959a93bce691fa1adebf474555   "/sc1_infer.sh"          4 days ago          Up 4 days                               7898165.bm16-1.SCORE_SC_1.SCORING
050af8b9102a        brucehoff/challengedockeragent                                                                                     "/bin/sh -c 'exec mvn"   4 days ago          Up 4 days                               bm16-score-2
26dc90b62b4d        docker.synapse.org/syn5644795/nvml-statsd                                                                          "/bin/sh -c 'python /"   2 weeks ago         Up 2 weeks                              nvml-statsd
b5b1e6de5fb2        sysdig/agent                                                                                                       "/docker-entrypoint.s"   2 weeks ago         Up 2 weeks                              sysdig-agent
[root@bm16 ~]#
```

**Comment by brucehoff** [comment]
No, it's not normal.  The agent stopped itself when it detected a mismatch between the state of the machine (a running container) and the state recorded in Synapse (no running containers, see below).  However the agent is mistaken:  Synapse does show 7898165 as running.  There is no mismatch.  I restarted the agent and now everything's fine.  I'm at a loss as to why the agent thought the state in Synapse was wrong.

```
java.lang.IllegalStateException: Container is running for submission 7898165 but evaluation 7453778 lists these running submissions for agent bm16-1: []
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:130)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:223)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
```
