### ISSUE TITLE
bm19 problem with Docker

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#466]
challenge agent bm19-train-2 stopped with the error:
{"message":"containerd: container did not start before the specified timeout"}
On bm19 there is a 'clean up' container that was created but not started.  It can't be removed:
```
$ docker ps -a
CONTAINER ID        IMAGE                                                                                                                                               COMMAND                  CREATED             STATUS                        PORTS               NAMES
b6feb467cd87        docker.synapse.org/syn5644795/dm-directory-clean                                                                                                    "/bin/bash /run.sh /d"   28 minutes ago      Created                                           8016978.bm19-2.directory-cleaner
7858d2c17fb6        docker.synapse.org/syn7816429/preprocessing@sha256:89827340b5cdaffc4f59ccfb8e090e3d1c82eac7f1f2b398256611ea33421d4a                                 "/preprocess.sh"         54 minutes ago      Exited (137) 35 minutes ago                       archive.8016862.bm19-2.TRAIN.PREPROCESSING
d80c7e3fb84a        docker.synapse.org/syn8015255/dm-preprocess-png-1000@sha256:086d0e52e88fb950e51b3bfdab95403d29b1b26e1b9c266650e60742d60e691b                        "/preprocess.sh"         5 hours ago         Up 5 hours                                        8015775.bm19-1.TRAIN.PREPROCESSING
c58a969c88ee        docker.synapse.org/syn7593674/dm-keras-preprocess@sha256:59b8576c89ac5f3013c51710908c203584a2ab039ea541fff9e30229fd38d767                           "/preprocess.sh"         6 hours ago         Exited (137) 3 hours ago                          archive.8015636.bm19-2.TRAIN.PREPROCESSING
a9b7be547ad1        docker.synapse.org/syn7993799/t1@sha256:379aecd67662af76c0af19b6de4d5f6955374832ef213ea330c2a82196211db4                                            "/train.sh"              21 hours ago        Exited (1) 20 hours ago                           archive.8013562.bm19-1.TRAIN.TRAINING
8fd5033ef93d        brucehoff/challengedockeragent                                                                                                                      "/bin/sh -c 'exec mvn"   23 hours ago        Exited (1) 26 minutes ago                         bm19-train-2
ae9c5439fa31        brucehoff/challengedockeragent                                                                                                                      "/bin/sh -c 'exec mvn"   23 hours ago        Up 23 hours                                       bm19-train-1
bce789fd0941        docker.synapse.org/syn7221819/sc1_pre_train_recover_of_recover_of_recover@sha256:8fa017adf95106c8e2659186c8fdbdd3734c0616fbc073680fb634cc7cf76655   "/train.sh"              27 hours ago        Exited (137) 27 hours ago                         archive.8011890.bm19-2.TRAIN.TRAINING
7e46d20900f6        docker.synapse.org/syn7221819/sc1_pre_train_recover_of_recover_of_recover@sha256:7852f8836a852bffeb8c342b7a9cf711d5423f5b29b1e3609bbb9abc4ea19570   "/train.sh"              28 hours ago        Exited (1) 28 hours ago                           archive.8011718.bm19-2.TRAIN.TRAINING
c0d49ecdc083        docker.synapse.org/syn7364819/blue@sha256:c928a341d892edb8fc621b28713bf833df774dbfa6d95e914b09747f054b431c                                          "/train.sh"              4 days ago          Exited (137) 2 days ago                           archive.7996146.bm19-1.TRAIN.TRAINING
0ac9169990e9        docker.synapse.org/syn7221819/sc1_pre_train_recover@sha256:05c86929adc4ce283a191232e58574832ca6cff459651e7885c84c324114a618                         "/train.sh"              7 days ago          Exited (1) 7 days ago                             archive.7992460.bm19-2.TRAIN.TRAINING
$ docker rm  8016978.bm19-2.directory-cleaner
Error response from daemon: Unable to remove filesystem for b6feb467cd872029704557e3ff5d23566f0288ab4dad821546878d6eb00dcd78: remove /var/lib/docker/containers/b6feb467cd872029704557e3ff5d23566f0288ab4dad821546878d6eb00dcd78/shm: device or resource busy
```

**Comment by tschaffter** [comment]
The container is no longer listed by `docker ps -a`. Does that solve the problem?

```
[root@bm19 ~]# docker ps -a
CONTAINER ID        IMAGE                                                                                                                                               COMMAND                  CREATED             STATUS                      PORTS               NAMES
7858d2c17fb6        docker.synapse.org/syn7816429/preprocessing@sha256:89827340b5cdaffc4f59ccfb8e090e3d1c82eac7f1f2b398256611ea33421d4a                                 "/preprocess.sh"         2 hours ago         Exited (137) 2 hours ago                        archive.8016862.bm19-2.TRAIN.PREPROCESSING
d80c7e3fb84a        docker.synapse.org/syn8015255/dm-preprocess-png-1000@sha256:086d0e52e88fb950e51b3bfdab95403d29b1b26e1b9c266650e60742d60e691b                        "/preprocess.sh"         7 hours ago         Up 7 hours                                      8015775.bm19-1.TRAIN.PREPROCESSING
c58a969c88ee        docker.synapse.org/syn7593674/dm-keras-preprocess@sha256:59b8576c89ac5f3013c51710908c203584a2ab039ea541fff9e30229fd38d767                           "/preprocess.sh"         8 hours ago         Exited (137) 5 hours ago                        archive.8015636.bm19-2.TRAIN.PREPROCESSING
a9b7be547ad1        docker.synapse.org/syn7993799/t1@sha256:379aecd67662af76c0af19b6de4d5f6955374832ef213ea330c2a82196211db4                                            "/train.sh"              23 hours ago        Exited (1) 22 hours ago                         archive.8013562.bm19-1.TRAIN.TRAINING
8fd5033ef93d        brucehoff/challengedockeragent                                                                                                                      "/bin/sh -c 'exec mvn"   25 hours ago        Exited (1) 2 hours ago                          bm19-train-2
ae9c5439fa31        brucehoff/challengedockeragent                                                                                                                      "/bin/sh -c 'exec mvn"   25 hours ago        Up 25 hours                                     bm19-train-1
bce789fd0941        docker.synapse.org/syn7221819/sc1_pre_train_recover_of_recover_of_recover@sha256:8fa017adf95106c8e2659186c8fdbdd3734c0616fbc073680fb634cc7cf76655   "/train.sh"              29 hours ago        Exited (137) 29 hours ago                       archive.8011890.bm19-2.TRAIN.TRAINING
7e46d20900f6        docker.synapse.org/syn7221819/sc1_pre_train_recover_of_recover_of_recover@sha256:7852f8836a852bffeb8c342b7a9cf711d5423f5b29b1e3609bbb9abc4ea19570   "/train.sh"              30 hours ago        Exited (1) 30 hours ago                         archive.8011718.bm19-2.TRAIN.TRAINING
c0d49ecdc083        docker.synapse.org/syn7364819/blue@sha256:c928a341d892edb8fc621b28713bf833df774dbfa6d95e914b09747f054b431c                                          "/train.sh"              4 days ago          Exited (137) 2 days ago                         archive.7996146.bm19-1.TRAIN.TRAINING
0ac9169990e9        docker.synapse.org/syn7221819/sc1_pre_train_recover@sha256:05c86929adc4ce283a191232e58574832ca6cff459651e7885c84c324114a618                         "/train.sh"              7 days ago          Exited (1) 7 days ago                           archive.7992460.bm19-2.TRAIN.TRAINING
[root@bm19 ~]# docker rm 8016978.bm19-2.directory-cleaner
Error response from daemon: No such container: 8016978.bm19-2.directory-cleaner
```

**Comment by brucehoff** [comment]
> Does that solve the problem?

No.  More recently another submission failed to run on bm19 for the same reason:

```
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"containerd: container did not start before the specified timeout"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
	at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:29)
	at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:12)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:46)
	at org.sagebionetworks.DockerUtils.startContainer(DockerUtils.java:302)
	at org.sagebionetworks.FileUtils.clearFileDirectory(FileUtils.java:53)
	at org.sagebionetworks.Training.startPreprocessing(Training.java:397)
```

**Comment by tschaffter** [comment]
The symptoms on bm19 are the same than describe here: #445 . It takes about 30 seconds to connect to the machine and systemctl is systematically timing out, which prevent commands like `service docker stop` or `reboot`. I think that this is the main last remaining issue that we have (no more crashes since we stopped using sysdig and clean the data more efficiently).

```
[root@bm19 ~]# vim /var/log/messages
Jan 13 17:40:01 bm19 systemd[1]: Stopping user-0.slice.
Jan 13 18:00:26 bm19 systemd-logind[1394]: Failed to start user slice: Connection timed out
Jan 13 18:00:26 bm19 auditd[1353]: Audit daemon rotating log files
Jan 13 18:00:42 bm19 MR_MONITOR[4932]: <MRMON044> Controller ID: 0  Time established since power on: Time 2017-01-13,18:00:42 1384551 Seconds
Jan 13 18:00:51 bm19 systemd-logind[1394]: Failed to start session scope session-1613.scope: Connection timed out (null)
Jan 13 18:00:51 bm19 systemctl[21361]: Failed to get properties: Connection timed out
Jan 13 18:00:51 bm19 systemctl[21373]: Failed to get properties: Connection timed out
Jan 13 18:01:26 bm19 systemd-logind[1394]: Failed to start user slice: Connection timed out
Jan 13 18:01:51 bm19 systemd-logind[1394]: Failed to start session scope session-1615.scope: Connection timed out (null)
Jan 13 18:01:51 bm19 systemctl[21421]: Failed to get properties: Connection timed out
Jan 13 18:02:16 bm19 systemctl[21439]: Failed to get properties: Connection timed out
Jan 13 18:02:41 bm19 systemctl[21454]: Failed to get properties: Connection timed out
Jan 13 18:03:06 bm19 systemctl[21477]: Failed to get properties: Connection timed out
Jan 13 18:20:26 bm19 systemd-logind[1394]: Failed to start user slice: Connection timed out
Jan 13 18:20:51 bm19 systemd-logind[1394]: Failed to start session scope session-1616.scope: Connection timed out (null)
Jan 13 18:20:51 bm19 systemctl[21508]: Failed to get properties: Connection timed out
Jan 13 18:40:26 bm19 systemd-logind[1394]: Failed to start user slice: Connection timed out
Jan 13 18:40:51 bm19 systemd-logind[1394]: Failed to start session scope session-1617.scope: Connection timed out (null)
Jan 13 18:40:51 bm19 systemctl[21541]: Failed to get properties: Connection timed out
Jan 13 19:00:27 bm19 systemd-logind[1394]: Failed to start user slice: Connection timed out
Jan 13 19:00:42 bm19 MR_MONITOR[4932]: <MRMON044> Controller ID: 0  Time established since power on: Time 2017-01-13,19:00:42 1388151 Seconds
Jan 13 19:00:52 bm19 systemd-logind[1394]: Failed to start session scope session-1618.scope: Connection timed out (null)
Jan 13 19:00:52 bm19 systemctl[21579]: Failed to get properties: Connection timed out
Jan 13 19:00:52 bm19 systemctl[21585]: Failed to get properties: Connection timed out
...
```

More information is following.

**Comment by tschaffter** [comment]
DST ticket: https://ticketing.dst.ibm.com/problem/view/196091

**Comment by brucehoff** [comment]
I'm taking a chance on bring bm19 back on line since (1) we are short on machines and (2) we have been getting a sense that this problem is not machine-specific, but perhaps caused by certain submissions.

**Comment by brucehoff** [comment]
I brought bm19 back on line but now have run into the problem where all containers spontaneously stopped:
```
docker ps -a
CONTAINER ID        IMAGE                                                                                                                                               COMMAND                  CREATED             STATUS                    PORTS               NAMES
85c904da666b        docker.synapse.org/syn7813569/train@sha256:ab814763f87c4694136963452a6a89eb3f2ed310d95522c81dc858dd1ac5aca7                                         "/train.sh"              10 hours ago        Exited (1) 9 hours ago                        8077071.bm19-2.TRAIN.TRAINING
03f913df54f8        docker.synapse.org/syn7813569/preprocess@sha256:cdaa2546e853667e2d31e2104cd6cd4bfddb3994887330ad924de8f9282ab6e5                                    "/preprocess.sh"         10 hours ago        Exited (0) 10 hours ago                       archive.8077071.bm19-2.TRAIN.PREPROCESSING
4edd826e3d6a        docker.synapse.org/syn8076503/dm-preprocess-227-aug@sha256:ff44ae84bfdd2d6a99f20d2757d615d824fde45ed696d7e48a68c46b5524e5e9                         "/preprocess.sh"         10 hours ago        Exited (1) 9 hours ago                        8077758.bm19-1.TRAIN.PREPROCESSING
effd668b7b91        brucehoff/challengedockeragent                                                                                                                      "/usr/local/bin/mvn-e"   10 hours ago        Exited (1) 9 hours ago                        bm19-train-2
154c48b55cf1        brucehoff/challengedockeragent                                                                                                                      "/usr/local/bin/mvn-e"   10 hours ago        Exited (1) 9 hours ago                        bm19-train-1
```

**Comment by tschaffter** [comment]
@brucehoff Please fill in https://docs.google.com/spreadsheets/d/16smwWa9UvueyuJbda98poNAe9DbVySC04uRq4s6Ghgg/edit#gid=0

**Comment by brucehoff** [comment]
> @brucehoff Please fill in https://docs.google.com/spreadsheets/d/16smwWa9UvueyuJbda98poNAe9DbVySC04uRq4s6Ghgg/edit#gid=0

Done.  FYI, nearly all the information for the spreadsheet is in the 'docker ps -a' results.  E.g. one of the stopped containers is '8077758.bm19-1.TRAIN.PREPROCESSING' which means it was submission ID 8077758 that ran on server bm19, agent no. 1.  (The name also says it was the preprocessing phase of a training submission.)  The only other piece of information for the spreadsheet is the submitting team which is retrieved from the dashboard: https://www.synapse.org/#!Synapse:syn5644795/wiki/405302 by looking up the Submission ID.

**Comment by brucehoff** [comment]
Looking at the last failure, the containers stopped 58min after 8077758 started and 48 min after 8077071 started.  I restarted 8077758 (on bm19-1) to see if it crashes the server again.  The agent picked up another submission to run, 8079967, but I will watch and see if 8077758 crashes when it (eventually) runs.

**Comment by brucehoff** [comment]
For now the machine is running.  Will revisit if/when the problem recurs.
