### ISSUE TITLE
Docker RMI failed when removing the secondary tag added for archiving

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#668]
```
> ss@annotations@stringAnnos[[2]]
An object of class "StringAnnotation"
Slot "autoGeneratedExtra":
list()

Slot "value":
[1] "{\"training\":\"docker.synapse.org/syn7344325/tmii_2017_02_27@sha256:2dd1511f7e9166a9ce6256c6f605ddf2a589f793f7322bd04fad14ffbc56ebf8\"}"

Slot "key":
[1] "TRAINING_SUBMISSION_PARAMETERS"

Slot "isPrivate":
[1] TRUE

```

```
{"message":"No such image: docker.synapse.org/syn7887977/8343693/training:latest"}

	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:239)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:172)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:224)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: docker.synapse.org/syn7887977/8343693/training:latest"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:27)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:11)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec(RemoveImageCmdImpl.java:64)
	at org.sagebionetworks.DockerUtils.removeImage(DockerUtils.java:411)
	at org.sagebionetworks.Training.startTraining(Training.java:571)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:427)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
	... 9 more
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Submission ID: 8343693
{"message":"No such image: docker.synapse.org/syn7887977/8343693/training:latest"}

	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:239)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:172)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:224)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	... 6 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: docker.synapse.org/syn7887977/8343693/training:latest"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:27)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:11)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec(RemoveImageCmdImpl.java:64)
	at org.sagebionetworks.DockerUtils.removeImage(DockerUtils.java:411)
	at org.sagebionetworks.Training.startTraining(Training.java:571)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:427)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
```

**Comment by brucehoff** [comment]
I'm pretty sure the root cause is: https://sagebionetworks.jira.com/browse/PLFM-4278  The agent has a check to keep the back end issue from letting two agents run the same submission and since that check was introduced there has been no recurrence.  So I think this issue can be closed, though PLFM-4278 still needs to be finished.
