### ISSUE TITLE
Container is running on bm07 but Synapse records it as running on bm22

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#669]
This is bizarre:  An agent on bm07 says that it started a container but in the Synapse evaluation queue it's recorded as running on bm22.  I checked bm22 and (thankfully) there is no container running there.

```
Submission  to TRAIN failed. Agent: bm07-1 

 The message is:

	Submission ID: 8343933
Container is running for submission 8343933 but Synapse shows that the submission has status EVALUATION_IN_PROGRESS and is assigned to agent bm22-1
```

**Comment by brucehoff** [comment]
8343933 DID run on bm22: 

```
docker ps -a
CONTAINER ID        IMAGE                                                                                                                               COMMAND                  CREATED             STATUS                         PORTS               NAMES
...
5cc4d5652da2        docker.synapse.org/syn7221819/sc1_pre_train_recover_5th@sha256:e8573a505dce978a057d1609fca1d006dcca9408e7690ea2df9d3bfd00589fc4     "/train.sh"              About an hour ago   Exited (1) About an hour ago                       archive.8343933.bm22-1.TRAIN.TRAINING
...
```
'docker inspect' shows the start and finish time stamps:
```
docker inspect 5cc4d5652da2
...
            "StartedAt": "2017-02-27T17:44:29.918825002Z",
            "FinishedAt": "2017-02-27T17:46:11.861729393Z"
...
```

```
docker ps -a
CONTAINER ID        IMAGE                                                                                                                                        COMMAND                  CREATED             STATUS                         PORTS               NAMES
7cad7dfddb2f        docker.synapse.org/syn7221819/sc1_pre_train_recover_5th@sha256:e8573a505dce978a057d1609fca1d006dcca9408e7690ea2df9d3bfd00589fc4              "/train.sh"              2 hours ago         Exited (1) 2 hours ago                             8343933.bm07-1.TRAIN.TRAINING

...
 docker inspect 7cad7dfddb2f

...
            "StartedAt": "2017-02-27T17:44:30.280453644Z",
            "FinishedAt": "2017-02-27T17:46:18.917409009Z"
                                                               
```

**Comment by brucehoff** [comment]
Note that the two containers started at the same time.  It looks like the two agents each assigned the job to themselves simultaneously.

Hypothesis:  We use submission annotations as a semaphore for control over a submission by the multiple, simultaneously running agents.  If we are checking assignment by looking at queryable annotations rather than the transactional data itself then we might think a submission is unassigned when it is actually assigned.

**Comment by brucehoff** [comment]
Another case occurred.  Here *both* agents on bm23 started the same container.  Here's the log from bm23-train-1:
```
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Selected submission  8357508
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Locked chosen submission.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Selected and locked 8357508 for TRAIN
03:16:04.822 [org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Mar 01, 2017 3:16:04 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Will not retry: 202 null
03:16:05.012 [org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Mar 01, 2017 3:16:05 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Will not retry: 202 null
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Training image: docker.synapse.org/syn8273321/iv3pid_0229_3k8_lall_do99_regl2_da8@sha256:283d4b5be0ca01cda5606d65f4f3ba52dae3fd80c44c31123619ec1ca4933b26
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.ChallengeDockerAgent - Top level loop: checking progress or starting new job.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.ChallengeDockerAgent - Precheck completed successfully.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Found a running training job.
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Training - Submission failed
java.lang.Exception: Submission ID: 8357508
Container is running for submission 8357508 but Synapse shows that the submission has status EVALUATION_IN_PROGRESS and is assigned to agent bm23-2
```
So it found the submission to be unassigned, assigned it to itself, and then found that it was assigned to bm23-2 (the other agent on the machine).  Here's the log for the other agent, bm23-train-2:

```

[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Submission 8356104
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Submission 8357508
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.validation.TrainingValidator - retrieveAndValidateTrainingParams
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - validating: docker.synapse.org/syn7823455/dpt8@sha256:9fca3caf3aca79310571e776a73ef21b297fc9dc971be2582a2e673bcab61503
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - done validating
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - validating: docker.synapse.org/syn8273321/iv3pid_0229_3k8_lall_do99_regl2_da8@sha256:283d4b5be0ca01cda5606d65f4f3ba52dae3fd80c44c31123619ec1ca4933b26
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - done validating
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.DockerUtils - DockerUtils.doesImageExist: docker.synapse.org/syn7823455/dpt8@sha256:9fca3caf3aca79310571e776a73ef21b297fc9dc971be2582a2e673bcab61503
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - validating: docker.synapse.org/syn7823455/dpt8@sha256:9fca3caf3aca79310571e776a73ef21b297fc9dc971be2582a2e673bcab61503
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - done validating
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.DockerUtils - DockerUtils.doesImageExist: Image is syntactically correct.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.DockerUtils - DockerUtils.doesImageExist: Registry returned status code 200
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.DockerUtils - DockerUtils.doesImageExist: docker.synapse.org/syn8273321/iv3pid_0229_3k8_lall_do99_regl2_da8@sha256:283d4b5be0ca01cda5606d65f4f3ba52dae3fd80c44c31123619ec1ca4933b26
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - validating: docker.synapse.org/syn8273321/iv3pid_0229_3k8_lall_do99_regl2_da8@sha256:283d4b5be0ca01cda5606d65f4f3ba52dae3fd80c44c31123619ec1ca4933b26
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - done validating
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.DockerUtils - DockerUtils.doesImageExist: Image is syntactically correct.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.DockerUtils - DockerUtils.doesImageExist: Registry returned status code 200
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - validating: docker.synapse.org/syn7823455/dpt8@sha256:9fca3caf3aca79310571e776a73ef21b297fc9dc971be2582a2e673bcab61503
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - done validating
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - validating: docker.synapse.org/syn8273321/iv3pid_0229_3k8_lall_do99_regl2_da8@sha256:283d4b5be0ca01cda5606d65f4f3ba52dae3fd80c44c31123619ec1ca4933b26
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.SubmissionUtils - done validating
03:15:16.625 [org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.client.SynapseProfileProxy - java.lang.reflect.InvocationTargetException
Mar 01, 2017 3:15:16 AM org.sagebionetworks.ExponentialBackoffRunner execute
SEVERE: Will not retry: 412 Submission Status: 8357508 was updated since you last fetched it, retrieve it again and reapply the update
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Done checking available submissions.  (chosenSubmission==null): true
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - No available submission meeting the criteria necessary to be run.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.ChallengeDockerAgent - Top level loop: checking progress or starting new job.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.ChallengeDockerAgent - Precheck completed successfully.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - No running training job found
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Number of received/validated submissions: 2
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Submission 8356104
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Submission 8357508
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Done checking available submissions.  (chosenSubmission==null): false
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Selected submission  8357508
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Locked chosen submission.
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Selected and locked 8357508 for TRAIN
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Training - Training image: docker.synapse.org/syn8273321/iv3pid_0229_3k8_lall_do99_regl2_da8@sha256:283d4b5be0ca01cda5606d65f4f3ba52dae3fd80c44c31123619ec1ca4933b26
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Training - Submission failed
java.lang.Exception: Submission ID: 8357508
{"message":"No such image: docker.synapse.org/syn7887972/8357508/training:latest"}

	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:239)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:172)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:224)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: docker.synapse.org/syn7887972/8357508/training:latest"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:27)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:11)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec(RemoveImageCmdImpl.java:64)
	at org.sagebionetworks.DockerUtils.removeImage(DockerUtils.java:411)
	at org.sagebionetworks.Training.startTraining(Training.java:571)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:427)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
	... 9 more
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Submission ID: 8357508
{"message":"No such image: docker.synapse.org/syn7887972/8357508/training:latest"}

	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:239)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:172)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:224)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	... 6 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: docker.synapse.org/syn7887972/8357508/training:latest"}

	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:47)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.delete(JerseyInvocation.java:360)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:27)
	at com.github.dockerjava.jaxrs.RemoveImageCmdExec.execute(RemoveImageCmdExec.java:11)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.RemoveImageCmdImpl.exec(RemoveImageCmdImpl.java:64)
	at org.sagebionetworks.DockerUtils.removeImage(DockerUtils.java:411)
	at org.sagebionetworks.Training.startTraining(Training.java:571)
	at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:427)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:205)
	... 9 more

```

**Comment by brucehoff** [comment]
More information about this bug:  We have captured a case in which getting all submissions, filtered on status (status=RECEIVED) returns at least one submissions with a different status:
```
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Training - Submission failed
java.lang.RuntimeException: Submission 8369798 has state VALIDATED when RECEIVED was expected.
	at org.sagebionetworks.EvaluationUtils.selectSubmissions(EvaluationUtils.java:323)
	at org.sagebionetworks.Training.selectAndLockSubmissionForTraining(Training.java:252)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:201)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:172)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:224)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Submission 8369798 has state VALIDATED when RECEIVED was expected.
	at org.sagebionetworks.EvaluationUtils.selectSubmissions(EvaluationUtils.java:323)
	at org.sagebionetworks.Training.selectAndLockSubmissionForTraining(Training.java:252)
	at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:201)
	at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:172)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:224)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	... 6 more
```

**Comment by brucehoff** [comment]
Going forward the problem is tracked here: https://sagebionetworks.jira.com/browse/PLFM-4278
