### ISSUE TITLE
bm02 is down due to having no space left on volume for images

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#68]
Failed to start preprocessing phase of 7435455.  Message is Could not pull image: write /var/lib/docker/tmp/GetImageBlob094853687: no space left on device
    at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:204)
    at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:155)
    at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:246)
    at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:745)

**Comment by tschaffter** [comment]
The filesystem is saturated because there are two many Docker images, which are by default saved to the filesystem.

[root@bm02 /]# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 155
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-503490611-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 96.26 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.562 GB
 Metadata Space Used: 136.5 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.562 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)

See #3
