### ISSUE TITLE
spurious errors uploading files

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#696]
This started happening more often.  Can probably be handled with a retry.
```
Caused by: org.sagebionetworks.client.exceptions.SynapseBadRequestException: Missing 1 part(s).  All parts must be successfully added before a file upload can be completed.
	at org.sagebionetworks.client.ClientUtils.throwException(ClientUtils.java:140)
	at org.sagebionetworks.client.ClientUtils.convertResponseBodyToJSONAndThrowException(ClientUtils.java:93)
	at org.sagebionetworks.client.BaseClientImpl.putJson(BaseClientImpl.java:446)
	at org.sagebionetworks.client.BaseClientImpl.putJSONEntity(BaseClientImpl.java:555)
	at org.sagebionetworks.client.SynapseClientImpl.completeMultipartUpload(SynapseClientImpl.java:4679)
	at org.sagebionetworks.client.MultipartUpload.uploadFile(MultipartUpload.java:96)
	at org.sagebionetworks.client.SynapseClientImpl.multipartUpload(SynapseClientImpl.java:4685)
	at org.sagebionetworks.client.SynapseClientImpl.multipartUpload(SynapseClientImpl.java:4699)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sagebionetworks.client.SynapseProfileProxy$SynapseInvocationHandler.invoke(SynapseProfileProxy.java:55)
	at com.sun.proxy.$Proxy27.multipartUpload(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sagebionetworks.SynapseClientFactory$1$1.execute(SynapseClientFactory.java:66)
	at org.sagebionetworks.ExponentialBackoffRunner.execute(ExponentialBackoffRunner.java:60)
	at org.sagebionetworks.SynapseClientFactory$1.invoke(SynapseClientFactory.java:54)
	at com.sun.proxy.$Proxy27.multipartUpload(Unknown Source)
	at org.sagebionetworks.Archiver.archiveToSynapse(Archiver.java:113)
	at org.sagebionetworks.Archiver.archiveLogsToSynapseWithSizeLimit(Archiver.java:257)
```

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/5de224d48d2514000f016bb9e9a4d3bcf6027ae7
