### ISSUE TITLE
Error unzipping model state file in inference submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#722]
```
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Scoring - Selected and locked 8481933 for SCORE_SC_1
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Scoring - Submission failed
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:904)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:287)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:140)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:228)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:904)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:287)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:140)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:228)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	... 6 more
```

**Comment by brucehoff** [comment]
Also happened here:
```
[org.sagebionetworks.ChallengeDockerAgent.main()] INFO org.sagebionetworks.Scoring - Selected and locked 8481970 for SCORE_SC_1
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Scoring - Submission failed
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:904)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:287)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:140)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:228)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:904)
	at org.fuin.utils4j.Utils4J.unzip(Utils4J.java:870)
	at org.sagebionetworks.Scoring.startScoreSubmission(Scoring.java:287)
	at org.sagebionetworks.Scoring.createOrUpdateScoringJob(Scoring.java:140)
	at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:228)
	at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:91)
	... 6 more
```

**Comment by brucehoff** [comment]
For 8481933 the model state file is syn8469385.
For 8481970 the model state file is also syn8469385.
Both were submitted by the same person.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/32dc293d1b69b7ce6216f84d383ad414bc0f2160
