### ISSUE TITLE
possible problems with p28x15 - p28x20

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#747]
YFG says:
```
Right before this submission, I tried on express lane: 8504022 it runs time out, then within 2 minutes, I didn't even change anything, I submitted to SC1, 8504218, how is it even possible that without running for one minute it failed?

in between, I didn't even do any change, any push to the repository.  so frustrating
```

Her logs:

```
...

    reraise(exc_type, exc_value, exc_trace)

  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 884, in __call__

    self.fn() if output_subset is None else\

RuntimeError: Cuda error: k_elemwise_unary_rowmajor_copy: unspecified launch failure. (n_blocks=3829, n_threads_per_block=256)



Apply node that caused the error: GpuAlloc(GpuElemwise{Composite{(i0 * (Composite{(((i0 - i1) * i2) + i3)}(i1, i2, i3, i4) + Abs(Composite{(((i0 - i1) * i2) + i3)}(i1, i2, i3, i4))))}}[(0, 1)].0, TensorConstant{1}, TensorConstant{16}, TensorConstant{175}, TensorConstant{175}, TensorConstant{2})

Toposort index: 225

Inputs types: [CudaNdarrayType(float32, (False, False, False, False, True)), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int8, scalar)]

Inputs shapes: [(1, 16, 175, 175, 1), (), (), (), (), ()]

Inputs strides: [(0, 30625, 175, 1, 0), (), (), (), (), ()]

Inputs values: ['not shown', array(1), array(16), array(175), array(175), array(2, dtype=int8)]

Outputs clients: [[Rebroadcast{0}(GpuAlloc.0)]]



HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

now all done

Died at SC1.3.2_512/combine_predictions.pl line 7.

diff 

0a1

> subjectId	laterality	confidence

prediction file



subjectId	laterality	confidence
```

We have a script on the `dmclient` machine to list running container:
```
#!/bin/sh
for m in $(docker-machine ls -q --filter STATE=Running)
do
	eval $(docker-machine env $m)
	echo '\n' $m
	docker ps  --format "{{.Names}} {{.Status}}"
done
```

The output shows that the nvidia-cloudwatch container is rebooting on p28x15-p28x19:
```
 bm01
nvml-cloudwatch Up 22 hours
bm01-train-2 Up 22 hours
8506953.bm01-2.TRAIN.PREPROCESSING Up 25 hours

...

 p28x15
8504081.p28x15-1.SCORE_SC_1.SCORING Up About an hour
8504018.p28x15-2.SCORE_SC_1.SCORING Up About an hour
**nvml-cloudwatch Restarting (1) 48 minutes ago**
p28x15-score-2 Up About an hour
p28x15-score-1 Up About an hour

 p28x16
8504082.p28x16-2.SCORE_SC_1.SCORING Up About an hour
8504122.p28x16-1.SCORE_SC_1.SCORING Up About an hour
**nvml-cloudwatch Restarting (1) 46 minutes ago**
p28x16-score-2 Up About an hour
p28x16-score-1 Up About an hour

 p28x17
8505132.p28x17-2.SCORE_SC_2.SCORING Up About an hour
8504696.p28x17-1.SCORE_SC_1.SCORING Up About an hour
**nvml-cloudwatch Restarting (1) 45 minutes ago**
p28x17-score-2 Up About an hour
p28x17-score-1 Up About an hour

 p28x18
8505408.p28x18-1.SCORE_SC_1.SCORING Up About an hour
8505030.p28x18-2.SCORE_SC_1.SCORING Up About an hour
**nvml-cloudwatch Restarting (1) 44 minutes ago**
p28x18-score-2 Up About an hour
p28x18-score-1 Up About an hour

 p28x19
8505832.p28x19-2.SCORE_SC_1.SCORING Up About an hour
8505629.p28x19-1.SCORE_SC_1.SCORING Up About an hour
**nvml-cloudwatch Restarting (1) 43 minutes ago**
p28x19-score-2 Up About an hour
p28x19-score-1 Up About an hour

 p28x20
**nvml-cloudwatch Restarting (1) 4 minutes ago**
p28x20-score-2 Up 32 minutes
p28x20-score-1 Up 32 minutes

 p28x21

```
Here is the tail of the log from one nvml-cloudwatch container:

```
...
Traceback (most recent call last):
  File "/main.py", line 51, in <module>
    sys.exit(main())
  File "/main.py", line 14, in main
    nvmlInit()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 608, in nvmlInit
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/main.py", line 51, in <module>
    sys.exit(main())
  File "/main.py", line 14, in main
    nvmlInit()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 608, in nvmlInit
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

```

YFG's submssion ran on p28x17.

I wonder if there is a problem with the configuration of the machines.  I have configured the agents on p28x15-p28x19 to stop after their current submission **but we may have to terminate and restart all submissions running on these machines to make sure they run properly.**

**Comment by brucehoff** [comment]
I have re-queued 8504218 in order to see if the outcome is different on a different machine.

**Comment by brucehoff** [comment]
There are three submissions that failed, all running on p28x17.  They have all been requeued.  In addition to 8504218, they are:
8504696
8505132
I will inform the participants.

**Comment by brucehoff** [comment]
@tschaffter I think we can close this.   If you agree, please close.

**Comment by tschaffter** [comment]
Waiting for reinstantiating p28x15 and p28x18.

**Comment by tschaffter** [comment]
p28x15 is no longer used. Terminated and being reinstantiated.

**Comment by tschaffter** [comment]
@brucehoff p28x15 has been terminated and re-instantiated (Leaderboard Inference). The agents can now be started. There is only p28x18 to replace once it's no longer processing submissions.

**Comment by tschaffter** [comment]
@brucehoff p28x18 has been replaced.
