### ISSUE TITLE
inference submission failed

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#748]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1879

**Comment by tschaffter** [comment]
@brucehoff If these submissions have been run on the five new machines, it may be safer to stop using them and further investigate what the problem is.

**Comment by brucehoff** [comment]
@tschaffter So far it seems that only p28x17 has affected submissions.  For now I will let submissions run on the other machines to see if they fail.  (I think there's no downside to doing this.)  However if you need to do maintenance on them we can certainly stop the submissions to make the machines available to you.

**Comment by tschaffter** [comment]
@brucehoff Thanks. Submissions on p28x16-19 can continue but I would make it so the agents shutdown once they are done. I'm currently working on the upgrade of the training machines and soon will have a look at p28x15.

**Comment by tschaffter** [comment]
@brucehoff p28x15 is running submissions. Can we take it offline so that I can investigate the issue?

**Comment by brucehoff** [comment]
@tschaffter I'm happy to help but why are you focussing on p28x15 when p28x17 is the most problematic server?

**Comment by tschaffter** [comment]
Sorry, I meant to investigate on the first of the five new machines (p28x15) but you are right, clues indicate to start with p28x17 even if it's supposed to have the same configuration than p28x15. I'll work with p28x17.

**Comment by brucehoff** [comment]
Sounds good.  It may help your investigation to see these errors from the nvml-cloudwatch container:
```
docker logs  nvml-cloudwatch --tail 30
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/main.py", line 51, in <module>
    sys.exit(main())
  File "/main.py", line 14, in main
    nvmlInit()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 608, in nvmlInit
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
Traceback (most recent call last):
  File "/main.py", line 51, in <module>
    sys.exit(main())
  File "/main.py", line 14, in main
    nvmlInit()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 608, in nvmlInit
    _LoadNvmlLibrary()
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 646, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/usr/local/lib/python2.7/site-packages/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

```

**Comment by brucehoff** [comment]
I think we can close this because the failed submissions on p28x17 were restarted on other machines and all other machines were updated (except for p28x18 which will be soon).
