### ISSUE TITLE
Two agents were able to assign a team to a server slot

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#76]
It should not be possible for two agents to assign a team to a slot.  One of them should get an optimistic concurrency error, yet it happened:

java.lang.Exception: Submission ID: 7435455
Expected zero or one row (slot) for team 3346508 but found 2
    at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:204)
    at org.sagebionetworks.Training.createOrUpdateTrainingJob(Training.java:155)
    at org.sagebionetworks.ChallengeDockerAgent.execute(ChallengeDockerAgent.java:246)
    at org.sagebionetworks.ChallengeDockerAgent.main(ChallengeDockerAgent.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected zero or one row (slot) for team 3346508 but found 2
    at org.sagebionetworks.Training.getTeamSlotStatus(Training.java:325)
    at org.sagebionetworks.Training.startPreprocessAndTrainSubmission(Training.java:417)
    at org.sagebionetworks.Training.createOrUpdateTrainingJobIntern(Training.java:190)
    ... 9 more

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/da43025b2c4a7791995353923475a0b0532008b9
