### ISSUE TITLE
Allow teams to host up to M preprocessed data on each machine

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#836]
Currently the challenge agent allows just one preprocessed data slot per team.  If a training submission uses a preprocessing step for which the output is cached in the slot, the slot's contents are used rather than rerunning preprocessing.  If the submission invokes another preprocessing step, then the slot is erased and made available and the new preprocessing step is run.

This logic could be generalized so that each team has up to 'M' slots.  If the preprocessing output required by a training submission is cached in any of a team's slots, then it is used.  Otherwise, if less than M slots have been used by the team and one is available, then the empty slot is assigned to the team and used to hold preprocessing output.  If M slots have been used (for other preprocessing output) then one would need to be freed for use.   The choice could be made by:
- freeing the oldest cached result
- freeing the cheapest (most quickly calculated) result
- not freeing any result, but requiring a slot to be manually freed

**Comment by tschaffter** [comment]
> freeing the oldest cached result
> freeing the cheapest (most quickly calculated) result
> not freeing any result, but requiring a slot to be manually freed
> The third choice is the best to avoid making a bad choice of which result to delete. If management > becomes too laborious, one of the other heuristics can be used instead.

+1

**Comment by brucehoff** [comment]
Current logic is:
```
A submission can be processed on this server if 
(1) there is no preprocessing required, or 
(2) there IS preprocessing required and one of:
(2a) the submitting team is assigned to a 'slot' on this server and
 	   (a) the preprocessing is done and the agent can get a read lock or
 	   (b) the preprocessing is not done and the agent can get a write lock;
(2b) the team isn't assigned to any slot on any server and this server has an unused slot;
(2c) (a) the team is assigned to another server and, 
 	   (b) the server is not actively using the assigned slot, and
 	   (c) the current submission uses different preprocessing, and 
 	   (d) the current server has a free slot.

```

New logic:  A submission can be processed on this server if
(1) there is no preprocessing required, or
(2) there is preprocessing required and one of:
(2a) the preprocessing is done in a slot on the server assigned to the team and the agent can get a read lock;
(2b) the preprocessing is not done or in progress in ANY slot assigned to the team on ANY server and the team has less than 'm' slots assigned to it and the server has an unused slot.

**Comment by brucehoff** [comment]
@tschaffter and @thomasyu888   I believe the code for supporting multiple slots is now complete.  It's a pretty significant change to the agent so I'd like (1) to set it up on a GPU server and make sure it works, then (2) roll it out to just one participant team to start.  @tschaffter is there a spare machine available that I could use to try out the new code?  Is there a particular team that has been vocal about needing to have multiple preprocessing variations to switch between dynamically?

**Comment by tschaffter** [comment]
> is there a spare machine available that I could use to try out the new code?
You can use bm04 and/or bm06 (space machines).

> Is there a particular team that has been vocal about needing to have multiple preprocessing variations to switch between dynamically?

Team "42 Is the answer". Multiple preprocessing variations is one element that must help them but its the team that would like read/write access to everything and consistency across all submissions.

**Comment by brucehoff** [comment]
Notes on testing / deployment:

I created a submission queue 9605910 in the Dry Run project (https://www.synapse.org/#!Synapse:syn5644795)

I created a script dmagent-mslots-experiment.sh from dmagentprod.sh, changing the training submission queue to the new one and removing inference queues.

I updated dmagent_core.sh adding the line "-e MAX_TEAM_SLOTS=8"

Started the agents on bm04 by running this:
```
./updateAgents.sh train ./dmagent-mslots-experiment.sh bm04
```

**Comment by brucehoff** [comment]
I updated the simple example: docker pull docker.synapse.org/syn5644795/dm-python-example (Synapse page: https://www.synapse.org/#!Synapse:syn7202722), made this training submission:
https://www.synapse.org/#!Synapse:syn10309807, and submitted it.

**Comment by brucehoff** [comment]
I made a trivial change to the model and rebuilt the Docker image, generating a new digest.  I uploaded a new submission file (v2 of https://www.synapse.org/#!Synapse:syn10309807) and submitted it.

**Comment by brucehoff** [comment]
I resubmitted the new version to double check that the agent can find the right preprocessing slot when reusing preprocessing results.

Result:  Agent  bm04-train-1 exited.  The logs show:
```
SEVERE: Will not retry: 400 TableId is required.
[org.sagebionetworks.ChallengeDockerAgent.main()] ERROR org.sagebionetworks.Training - Submission failed
org.sagebionetworks.client.exceptions.SynapseBadRequestException: TableId is required.
...
	at org.sagebionetworks.client.SynapseClientImpl.appendRowsToTable(SynapseClientImpl.java:3518)
...
	at org.sagebionetworks.Training.selectAndLockSubmissionForTraining(Training.java:355)
```

**Comment by brucehoff** [comment]
Patched the agent and tried again:  This time it worked and I verified that the agent used the correct preprocessing slot.

**Comment by brucehoff** [comment]
@tschaffter is this where you track which teams use which servers?
https://docs.google.com/spreadsheets/d/1uhYW9p1VssV2pekhNix5lRp6_gAA3x7QPLYvREbAMUw/edit#gid=0
If so, then it looks like "42 Is the answer" uses bm03 and bm21.

@thomasyu888 I need your help for the next step:  Would you please check that there are no submissions running then update and restart the agents on this team's machines?  Afterwards 'docker images --digests' should change from showing this:
```
brucehoff/challengedockeragent                                                      latest              sha256:7da09a2163c0b3b8daab5e1ff82239bfe5dca8a8bdcb28ce9f5f71b40f62ab48   2328e01f10b7        3 weeks ago         654 MB
```
to showing this:
```
brucehoff/challengedockeragent                     latest              sha256:f4f24572a1049c486406274f55bf0156b4295118b5c186e79258e2242aff2a1c   9f77c0e3aec0        21 minutes ago      654 MB
```

That is, the version of the updated agent code is `sha256:f4f24572a1049c486406274f55bf0156b4295118b5c186e79258e2242aff2a1c`.

Please let me know if you have any questions.

**Comment by tschaffter** [comment]
Each GPU server has 4 partitions `/data/datasetX` where x in [0,3].

> is this where you track which teams use which servers?
> https://docs.google.com/spreadsheets/d/1uhYW9p1VssV2pekhNix5lRp6_gAA3x7QPLYvREbAMUw/edit#gid=0

Yes. This is the correct document.

@brucehoff Can you please document this update on the wiki as well as all information related to the operation of the M slots.

https://www.synapse.org/#!Synapse:syn9935146/wiki/

We have the weekly meeting tomorrow. This would be great to introduce the change at that occasion.

**Comment by brucehoff** [comment]
@tschaffter The documentation and announcement are great ideas, but I first would like to try it out with one "guinea pig", i.e. the "42..." team.

**Comment by tschaffter** [comment]
OK. Have you contacted them?

**Comment by brucehoff** [comment]
@tschaffter No, please see the 'next steps' I listed above.  I need Tom to rerun the script he used to start the agents.

**Comment by thomasyu888** [comment]
I updated the agents!

**Comment by brucehoff** [comment]
Checked that the agents were restarted.  I see that they were, indeed, restarted about an hour ago.  Also there are submissions that started two hours ago.  This could cause a problem if in the preprocessing stage, but the submissions seem to be in the training stage so maybe things will work out OK.
```
ubuntu@ip-172-31-59-223:~$ docker ps
CONTAINER ID        IMAGE                                                                                                                                               COMMAND                  CREATED             STATUS              PORTS               NAMES
7a1d675f6177        docker.synapse.org/syn5644795/nvml-cloudwatch                                                                                                       "/bin/sh -c 'python /"   51 minutes ago      Up About an hour                        nvml-cloudwatch
84728669ad32        brucehoff/challengedockeragent                                                                                                                      "/usr/local/bin/mvn-e"   51 minutes ago      Up About an hour                        bm03-train-and-score-2
1957df062613        brucehoff/challengedockeragent                                                                                                                      "/usr/local/bin/mvn-e"   51 minutes ago      Up About an hour                        bm03-train-and-score-1
b9062f80f055        docker.synapse.org/syn7349799/forty3_is_the_answer_two_layer_image_frozen@sha256:4764d74cf7b2740da061176216985d0449cdd725926a93e90e521db23c7d36ca   "/train.sh"              About an hour ago   Up 2 hours                              9627443.bm03-2.TRAIN.TRAINING
0e6fd004b464        docker.synapse.org/syn7349799/forty2_is_the_answer_two_layer_image_frozen@sha256:38e1f6eec458e6ee814c27f674c2fc21539817978401e64b8522a5a88f3876eb   "/train.sh"              2 hours ago         Up 2 hours                              9627442.bm03-1.TRAIN.TRAINING
ubuntu@ip-172-31-59-223:~$ eval $(docker-machine env bm21)
ubuntu@ip-172-31-59-223:~$ docker ps
CONTAINER ID        IMAGE                                                                                                                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
74a442528e7b        docker.synapse.org/syn7349799/forty3_is_the_answer_two_layer_image_free@sha256:39e15ea0e0462f0496ca546ec1139609769a703757e0dbb094d2d9b19a84c482   "/train.sh"              52 minutes ago      Up About an hour                        9627474.bm21-2.TRAIN.TRAINING
00a069a2474e        docker.synapse.org/syn5644795/nvml-cloudwatch                                                                                                     "/bin/sh -c 'python /"   54 minutes ago      Up About an hour                        nvml-cloudwatch
67ef148c0ad2        brucehoff/challengedockeragent                                                                                                                    "/usr/local/bin/mvn-e"   55 minutes ago      Up About an hour                        bm21-train-and-score-2
5df77f2a37ba        brucehoff/challengedockeragent                                                                                                                    "/usr/local/bin/mvn-e"   55 minutes ago      Up About an hour                        bm21-train-and-score-1
faa8af87bc6f        docker.synapse.org/syn7349799/forty2_is_the_answer_two_layer_image_free@sha256:aa3a8d9d0cd312a9d5f0e41033fa90347c6dd0be8f565e2516b9eb39ec8d8295   "/train.sh"              About an hour ago   Up 2 hours                              9627444.bm21-1.TRAIN.TRAINING
```

**Comment by brucehoff** [comment]
Checking the version of the agent on the two machines.  First bm03:
```
brucehoff/challengedockeragent                                                      latest              sha256:f4f24572a1049c486406274f55bf0156b4295118b5c186e79258e2242aff2a1c   9f77c0e3aec0        20 hours ago        654 MB
```
Now bm21:
```
brucehoff/challengedockeragent                                                      latest              sha256:f4f24572a1049c486406274f55bf0156b4295118b5c186e79258e2242aff2a1c   9f77c0e3aec0        20 hours ago        654 MB
```
Perfect!

**Comment by brucehoff** [comment]
Used `docker inspect bm03-train-and-score-1` and -2 to check that the environment setting `MAX_TEAM_SLOTS=8` is used. (Ditto for the two agents on bm21.)  I see that https://www.synapse.org/#!Synapse:syn10240580/tables/ is the server slot table for bm03 and https://www.synapse.org/#!Synapse:syn10183970/tables/ is for bm21.

**Comment by brucehoff** [comment]
I emailed Team 42 Is the Answer:
>Dear Team "42 Is the Answer":
>
>Until now the IT infrastructure for the Digital Mammography challenge allowed just one preprocessing variation to be 'cached' on a GPU server.  We have now updated the infrastructure to allow up to four preprocessing variations per server.  Please refer to this table:
https://www.synapse.org/#!Synapse:syn10240580/tables/
Each of the four rows represents one 10TB volume for holding preprocessing data on the machine bm03.  Similarly, this table:
https://www.synapse.org/#!Synapse:syn10183970/tables/
shows the four volumes on bm21.  At this moment just one variation is used.  But now, when you submit a new training job using a different preprocessing step, the system will write the preprocessing output to an unused volume.  If you then seek to use the original preprocessing output it will no longer have to be recomputed.
>
>We are hoping that you can exercise this new feature in the next few days and report back as to whether it works to your satisfaction.  Afterwards we will deploy the feature to the rest of the collaborative community.  If you have any questions, please ask.
>
>Best,
>
>Bruce Hoff
Digital Mammography Challenge Administration

**Comment by brucehoff** [comment]
Remaining work:
Once Team 42 confirms the feature works correctly:
1) Update wiki: https://www.synapse.org/#!Synapse:syn9935146/wiki/
2) Send announcement to all teams.

**Comment by brucehoff** [comment]
@thomasyu888 Team 42 has confirmed that the feature works for them.  Will you please update the challenge agents on the other machines?  As mentioned above it's important to do so when submissions are not running (specifically when *preprocessing* is not running).  Once you've done this, please let me know.  I will then update the documentation, etc.
